import type { Metadata } from "next";
import { Oxanium } from 'next/font/google'
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ProductContextProvider } from "@/Context/productContext";
import { SingleProductProvider } from "@/Context/singleProductContext";
import { use } from "react";
import { UserProvider } from "@/Context/userContext";
import { Toaster } from "react-hot-toast";

interface Props {
  params: { _id: string };
}

const oxanium = Oxanium({
  subsets: ['latin'],
  variable: "--font-oxanium",
  weight: ['200', '300', '400', '500'],
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode; params: Props["params"];
}>) {

  const param = params
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-right"/>
          <UserProvider>
            <ProductContextProvider>
              <SingleProductProvider>
                <div className="relative">
                  <Navbar/>
                    {children}
                  <Footer/>
                </div>
              </SingleProductProvider>
            </ProductContextProvider>
          </UserProvider>
      </body>
    </html>
  );
}
