/* eslint-disable */

import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import StoreProvider from "./storeProvider";

interface Props {
  params: { _id: string };
}

const oxanium = Oxanium({
  subsets: ["latin"],
  variable: "--font-oxanium",
  weight: ["200", "300", "400", "500", "600","700", "800"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Props["params"];
}>) {
  const param = params;
  return (
    <html lang="en">
      <body
        className={`${oxanium.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-right"/>
          <StoreProvider>
            <div className="relative">
              <Navbar />
              {children}
            </div>
          </StoreProvider>
      </body>
    </html>
  );
}
